name: Auto Sync Miao-Plugin Updates

on: 
  schedule: 
    - cron: '0 16 * * *'  # 北京时间 00:00
    - cron: '0 22 * * *'  # 北京时间 06:00
    - cron: '0 4  * * *'  # 北京时间 12:00
    - cron: '0 10 * * *'  # 北京时间 18:00
  workflow_dispatch:

jobs: 
  sync: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git remote | grep upstream || git remote add upstream https://github.com/yoimiya-kokomi/miao-plugin.git
          git fetch upstream

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge upstream/master into master
        id: merge
        run: |
          OUTPUT=$(git merge upstream/master --no-edit --allow-unrelated-histories 2>&1 || true)
          echo "$OUTPUT"
          echo "merge_result<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          git push origin master || true

      - name: Patch calc.js with effect templates
        run: |
          node .github/scripts/addEffectTemplates.cjs

      - name: Send DingTalk notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          REPO="${{ github.repository }}"
          MERGE_LOG=$(echo "${{ steps.merge.outputs.merge_result }}" | tail -n 10)

          curl -s -X POST "${{ secrets.DINGTALK_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "BiliBili【'"${REPO}"'】Miao-Plugin 同步任务完成。\nmaster分支合并上游日志：\n'"${MERGE_LOG}"'"
                }
              }'
